using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace RestaurantManagerAPI.Models;

/// <summary>
/// Represents a <c>MenuItem</c> in the restaurant menu.
/// </summary>
/// <author>Even Johan Pereira Haslerud</author>
/// <date>29.08.2024</date>
public class MenuItem
{
    /// <summary>
    /// Gets or sets the unique identifier for the Menu Item.
    /// This identifier is auto-generated by the database and
    /// serves as the primary key.
    /// </summary>
    /// <value>
    /// The unique identifier for the Menu Item, which must be
    /// a positive integer greater than zero.
    /// </value>
    /// <example>1</example>
    [Required(ErrorMessage = "Id is required.")]
    [Range(1, int.MaxValue, ErrorMessage = "Id must be greater than 0.")]
    public int Id { get; set; }

    /// <summary>
    /// Gets or sets the name of the Menu Item. The name is a
    /// required field and should not contain any numeric values.
    /// </summary>
    /// <value>
    /// A string representing the name of the Menu Item. It must
    /// be a valid string containing only alphabetical characters
    /// and spaces.
    /// </value>
    /// <example>Grilled Chicken Sandwich</example>
    [Required(ErrorMessage = "Name is required.")]
    [RegularExpression(@"^[a-zA-Z\s]+$", ErrorMessage = "Name cannot contain numbers.")]
    public string Name { get; set; }

    /// <summary>
    /// Gets or sets the list of product IDs associated with this
    /// Menu Item. This list represents the IDs of products that are
    /// required to prepare this menu item.
    /// </summary>
    /// <value>
    /// A list of integers where each integer is the unique identifier
    /// of a product associated with the Menu Item.
    /// </value>
    /// <example>
    /// [1, 2, 3]
    /// </example>
    public List<int> ProductIds { get; set; } = new List<int>();

    /// <summary>
    /// Gets or sets the list of <c>Product</c> objects associated with
    /// this Menu Item. This list represents the products required to
    /// prepare this Menu Item.
    /// </summary>
    /// <value>
    /// A list of <c>Product</c> objects that are part of the Menu Item.
    /// </value>
    /// <example>[Product1, Product2, Product3]</example>
    public List<MenuItemProduct> MenuItemProducts { get; set; } = new List<MenuItemProduct>();

    /// <summary>
    /// Gets or sets the list of <c>OrderMenuItem</c> objects associated
    /// with this Menu Item. This list represents the orders that include
    /// this Menu Item.
    /// </summary>
    /// <value>
    /// A list of <c>OrderMenuItem</c> objects that are part of the Menu Item.
    /// </value>
    /// <example>[OrderMenuItem1, OrderMenuItem2, OrderMenuItem3]</example>
    public List<OrderMenuItem> OrderMenuItems { get; set; } = new List<OrderMenuItem>();
}
