using System.ComponentModel.DataAnnotations;

namespace RestaurantManagerAPI.Models;

/// <summary>
/// Represents a <c>Order</c> in the restaurant menu.
/// </summary>
/// <author>Even Johan Pereira Haslerud</author>
/// <date>30.08.2024</date>
public class Order {

    /// <summary>
    /// Gets or sets the unique identifier for the Order.
    /// This identifier is auto-generated by the database and
    /// serves as the primary key.
    /// </summary>
    /// <value>
    /// The unique identifier for the Order, which must be
    /// a positive integer greater than zero.
    /// </value>
    /// <example>1</example>
    public int Id { get; set; }

    /// <summary>
    /// Sets the Date Time of the Order. The Date Time is
    /// a required filed and should be a format.
    /// </summary>
    /// <value>
    /// A DateTime representing the Date Time of the Order.
    /// </value>
    /// <example>2021-08-30T12:00:00</example>
    [Required(ErrorMessage = "DateTime is required.")]
    public DateTime DateTime { get; set; }

    /// <summary>
    /// Gets the list of the menu item IDs associated with
    /// this Order.
    /// </summary>
    /// <value>
    /// A list of integers, where each integer is the unique
    /// identifier of a menu item that is part of the order.
    /// </value>
    /// <example>
    /// [1, 2, 3]
    /// </example>
    [Required]
    public List<OrderMenuItem> OrderMenuItems { get; set; } = new List<OrderMenuItem>();
}