name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore src.generated.sln
      working-directory: ./rm-api/RestaurantManagerAPI/src

    - name: Build solution
      run: dotnet build --no-restore src.generated.sln
      working-directory: ./rm-api/RestaurantManagerAPI/src

    - name: Run tests
      run: dotnet test --no-build --verbosity normal src.generated.sln
      working-directory: ./rm-api/RestaurantManagerAPI

